# nanodet-EfficientNet-Lite1_416
# COCO mAP(0.5:0.95) = 0.303
#             AP_50  = 0.471
#             AP_75  = 0.313
#           AP_small = 0.122
#               AP_m = 0.321
#               AP_l = 0.432
save_dir: workspace/VovNet/nanodet-VovNet19b_slim_small_416
model:
  arch:
    name: GFL
    backbone:
      name: VovNet19b_slim
    fpn:
      name: PAN
      in_channels: [128, 144, 160]
      out_channels: 64
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 64
      feat_channels: 64
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    ......
