# nanodet-EfficientNet-Lite1_416
# COCO mAP(0.5:0.95) = 0.303
#             AP_50  = 0.471
#             AP_75  = 0.313
#           AP_small = 0.122
#               AP_m = 0.321
#               AP_l = 0.432
save_dir: workspace/VovNet/nanodet-VovNet19b_slim_half64_hoa_416
model:
  arch:
    name: GFL
    backbone:
      name: VovNet19b_slim
    fpn:
      name: PAN
      in_channels: [128, 144, 160]
      out_channels: 64
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 64
      feat_channels: 64
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: /mnt/hdd-4t/data/yq/dataset/head/channel_head_manual/train_image
    ann_path: /mnt/hdd-4t/data/yq/dataset/head/channel_head_manual/train_json/channel_head_train_20210308.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.5, 1.5]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.63, 57.63, 57.63]]
  val:
    name: coco
    img_path: /mnt/hdd-4t/data/yq/dataset/head/channel_head_Add_manual_roy/test_image
    ann_path: /mnt/hdd-4t/data/yq/dataset/head/channel_head_Add_manual_roy/test_json/channel_head_test.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.63, 57.63, 57.63]]
device:
  gpu_ids: [0,1]
  workers_per_gpu: 4
  batchsize_per_gpu: 10
schedule:
  #resume:
  #load_model: weights/nanodet-EfficientNet-Lite1_416.pth
  optimizer:
    name: SGD
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.01
  total_epochs: 190
  lr_schedule:
    name: MultiStepLR
    milestones: [130,150,160,165]
    gamma: 0.1
  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['head']
