#Config File example
save_dir: workspace/efficient/nanodet_efcnet128_416
model:
  arch:
    name: GFL
    backbone:
      name: EfficientNetLite128
      model_name: efficientnet_lite0
      out_stages: [2,4,6]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [40, 80, 128]
      out_channels: 64
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 64
      feat_channels: 64
      stacked_convs: 1
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    ......
